language: ruby
script: "bundle exec rspec spec"
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.3
gemfile:
  - Gemfile
notifications:
  recipients:
    - matt@thrivesmart.com
branches:
  only:
    - master
